//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente1.WsExt2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://xxx.pt/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xxx.pt/", ConfigurationName="WsExt2.CalcPlusSoap")]
    public interface CalcPlusSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Power", ReplyAction="*")]
        double Power(int b, int e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Power", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PowerAsync(int b, int e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Soma", ReplyAction="*")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Soma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomaAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name CurrenciesResult from namespace http://xxx.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Currencies", ReplyAction="*")]
        Cliente1.WsExt2.CurrenciesResponse Currencies(Cliente1.WsExt2.CurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xxx.pt/Currencies", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente1.WsExt2.CurrenciesResponse> CurrenciesAsync(Cliente1.WsExt2.CurrenciesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Currencies", Namespace="http://xxx.pt/", Order=0)]
        public Cliente1.WsExt2.CurrenciesRequestBody Body;
        
        public CurrenciesRequest() {
        }
        
        public CurrenciesRequest(Cliente1.WsExt2.CurrenciesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CurrenciesRequestBody {
        
        public CurrenciesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrenciesResponse", Namespace="http://xxx.pt/", Order=0)]
        public Cliente1.WsExt2.CurrenciesResponseBody Body;
        
        public CurrenciesResponse() {
        }
        
        public CurrenciesResponse(Cliente1.WsExt2.CurrenciesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://xxx.pt/")]
    public partial class CurrenciesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente1.WsExt2.ArrayOfString CurrenciesResult;
        
        public CurrenciesResponseBody() {
        }
        
        public CurrenciesResponseBody(Cliente1.WsExt2.ArrayOfString CurrenciesResult) {
            this.CurrenciesResult = CurrenciesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcPlusSoapChannel : Cliente1.WsExt2.CalcPlusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcPlusSoapClient : System.ServiceModel.ClientBase<Cliente1.WsExt2.CalcPlusSoap>, Cliente1.WsExt2.CalcPlusSoap {
        
        public CalcPlusSoapClient() {
        }
        
        public CalcPlusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcPlusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcPlusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcPlusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Power(int b, int e) {
            return base.Channel.Power(b, e);
        }
        
        public System.Threading.Tasks.Task<double> PowerAsync(int b, int e) {
            return base.Channel.PowerAsync(b, e);
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomaAsync(int x, int y) {
            return base.Channel.SomaAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente1.WsExt2.CurrenciesResponse Cliente1.WsExt2.CalcPlusSoap.Currencies(Cliente1.WsExt2.CurrenciesRequest request) {
            return base.Channel.Currencies(request);
        }
        
        public Cliente1.WsExt2.ArrayOfString Currencies() {
            Cliente1.WsExt2.CurrenciesRequest inValue = new Cliente1.WsExt2.CurrenciesRequest();
            inValue.Body = new Cliente1.WsExt2.CurrenciesRequestBody();
            Cliente1.WsExt2.CurrenciesResponse retVal = ((Cliente1.WsExt2.CalcPlusSoap)(this)).Currencies(inValue);
            return retVal.Body.CurrenciesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente1.WsExt2.CurrenciesResponse> Cliente1.WsExt2.CalcPlusSoap.CurrenciesAsync(Cliente1.WsExt2.CurrenciesRequest request) {
            return base.Channel.CurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente1.WsExt2.CurrenciesResponse> CurrenciesAsync() {
            Cliente1.WsExt2.CurrenciesRequest inValue = new Cliente1.WsExt2.CurrenciesRequest();
            inValue.Body = new Cliente1.WsExt2.CurrenciesRequestBody();
            return ((Cliente1.WsExt2.CalcPlusSoap)(this)).CurrenciesAsync(inValue);
        }
    }
}
