//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente1.WsExt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SomaProd", Namespace="http://www.ipca.pt/isi/")]
    [System.SerializableAttribute()]
    public partial class SomaProd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PField;
        
        private int SField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int P {
            get {
                return this.PField;
            }
            set {
                if ((this.PField.Equals(value) != true)) {
                    this.PField = value;
                    this.RaisePropertyChanged("P");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int S {
            get {
                return this.SField;
            }
            set {
                if ((this.SField.Equals(value) != true)) {
                    this.SField = value;
                    this.RaisePropertyChanged("S");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ipca.pt/isi/", ConfigurationName="WsExt.SomaSoap")]
    public interface SomaSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (SaySomething) of message SaySomething does not match the default value (HelloWorld)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/SaySomething", ReplyAction="*")]
        Cliente1.WsExt.SaySomething1 HelloWorld(Cliente1.WsExt.SaySomething request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/SaySomething", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente1.WsExt.SaySomething1> HelloWorldAsync(Cliente1.WsExt.SaySomething request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/Somar", ReplyAction="*")]
        int Somar(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/Somar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SomarAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/Multiplica", ReplyAction="*")]
        int Multiplica(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/Multiplica", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplicaAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name SomaEMultiplicaResult from namespace http://www.ipca.pt/isi/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/SomaEMultiplica", ReplyAction="*")]
        Cliente1.WsExt.SomaEMultiplicaResponse SomaEMultiplica(Cliente1.WsExt.SomaEMultiplicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ipca.pt/isi/SomaEMultiplica", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente1.WsExt.SomaEMultiplicaResponse> SomaEMultiplicaAsync(Cliente1.WsExt.SomaEMultiplicaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaySomething", WrapperNamespace="http://www.ipca.pt/isi/", IsWrapped=true)]
    public partial class SaySomething {
        
        public SaySomething() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaySomethingResponse", WrapperNamespace="http://www.ipca.pt/isi/", IsWrapped=true)]
    public partial class SaySomething1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ipca.pt/isi/", Order=0)]
        public string SaySomethingResult;
        
        public SaySomething1() {
        }
        
        public SaySomething1(string SaySomethingResult) {
            this.SaySomethingResult = SaySomethingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaEMultiplicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomaEMultiplica", Namespace="http://www.ipca.pt/isi/", Order=0)]
        public Cliente1.WsExt.SomaEMultiplicaRequestBody Body;
        
        public SomaEMultiplicaRequest() {
        }
        
        public SomaEMultiplicaRequest(Cliente1.WsExt.SomaEMultiplicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ipca.pt/isi/")]
    public partial class SomaEMultiplicaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public SomaEMultiplicaRequestBody() {
        }
        
        public SomaEMultiplicaRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SomaEMultiplicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SomaEMultiplicaResponse", Namespace="http://www.ipca.pt/isi/", Order=0)]
        public Cliente1.WsExt.SomaEMultiplicaResponseBody Body;
        
        public SomaEMultiplicaResponse() {
        }
        
        public SomaEMultiplicaResponse(Cliente1.WsExt.SomaEMultiplicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.ipca.pt/isi/")]
    public partial class SomaEMultiplicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente1.WsExt.SomaProd SomaEMultiplicaResult;
        
        public SomaEMultiplicaResponseBody() {
        }
        
        public SomaEMultiplicaResponseBody(Cliente1.WsExt.SomaProd SomaEMultiplicaResult) {
            this.SomaEMultiplicaResult = SomaEMultiplicaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SomaSoapChannel : Cliente1.WsExt.SomaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SomaSoapClient : System.ServiceModel.ClientBase<Cliente1.WsExt.SomaSoap>, Cliente1.WsExt.SomaSoap {
        
        public SomaSoapClient() {
        }
        
        public SomaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SomaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SomaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente1.WsExt.SaySomething1 Cliente1.WsExt.SomaSoap.HelloWorld(Cliente1.WsExt.SaySomething request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Cliente1.WsExt.SaySomething inValue = new Cliente1.WsExt.SaySomething();
            Cliente1.WsExt.SaySomething1 retVal = ((Cliente1.WsExt.SomaSoap)(this)).HelloWorld(inValue);
            return retVal.SaySomethingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente1.WsExt.SaySomething1> Cliente1.WsExt.SomaSoap.HelloWorldAsync(Cliente1.WsExt.SaySomething request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente1.WsExt.SaySomething1> HelloWorldAsync() {
            Cliente1.WsExt.SaySomething inValue = new Cliente1.WsExt.SaySomething();
            return ((Cliente1.WsExt.SomaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Somar(int x, int y) {
            return base.Channel.Somar(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomarAsync(int x, int y) {
            return base.Channel.SomarAsync(x, y);
        }
        
        public int Multiplica(int x, int y) {
            return base.Channel.Multiplica(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicaAsync(int x, int y) {
            return base.Channel.MultiplicaAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente1.WsExt.SomaEMultiplicaResponse Cliente1.WsExt.SomaSoap.SomaEMultiplica(Cliente1.WsExt.SomaEMultiplicaRequest request) {
            return base.Channel.SomaEMultiplica(request);
        }
        
        public Cliente1.WsExt.SomaProd SomaEMultiplica(int x, int y) {
            Cliente1.WsExt.SomaEMultiplicaRequest inValue = new Cliente1.WsExt.SomaEMultiplicaRequest();
            inValue.Body = new Cliente1.WsExt.SomaEMultiplicaRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            Cliente1.WsExt.SomaEMultiplicaResponse retVal = ((Cliente1.WsExt.SomaSoap)(this)).SomaEMultiplica(inValue);
            return retVal.Body.SomaEMultiplicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente1.WsExt.SomaEMultiplicaResponse> Cliente1.WsExt.SomaSoap.SomaEMultiplicaAsync(Cliente1.WsExt.SomaEMultiplicaRequest request) {
            return base.Channel.SomaEMultiplicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente1.WsExt.SomaEMultiplicaResponse> SomaEMultiplicaAsync(int x, int y) {
            Cliente1.WsExt.SomaEMultiplicaRequest inValue = new Cliente1.WsExt.SomaEMultiplicaRequest();
            inValue.Body = new Cliente1.WsExt.SomaEMultiplicaRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Cliente1.WsExt.SomaSoap)(this)).SomaEMultiplicaAsync(inValue);
        }
    }
}
