//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWCF.XXX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XXX.ICalc")]
    public interface ICalc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/Soma", ReplyAction="http://tempuri.org/ICalc/SomaResponse")]
        int Soma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/Soma", ReplyAction="http://tempuri.org/ICalc/SomaResponse")]
        System.Threading.Tasks.Task<int> SomaAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetPessoa", ReplyAction="http://tempuri.org/ICalc/GetPessoaResponse")]
        ClientWCF.XXX.Pessoa GetPessoa(string nome, int idade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetPessoa", ReplyAction="http://tempuri.org/ICalc/GetPessoaResponse")]
        System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa> GetPessoaAsync(string nome, int idade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetAll", ReplyAction="http://tempuri.org/ICalc/GetAllResponse")]
        ClientWCF.XXX.Pessoa[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetAll", ReplyAction="http://tempuri.org/ICalc/GetAllResponse")]
        System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetPessoas", ReplyAction="http://tempuri.org/ICalc/GetPessoasResponse")]
        ClientWCF.XXX.Pessoa[] GetPessoas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalc/GetPessoas", ReplyAction="http://tempuri.org/ICalc/GetPessoasResponse")]
        System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa[]> GetPessoasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcChannel : ClientWCF.XXX.ICalc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcClient : System.ServiceModel.ClientBase<ClientWCF.XXX.ICalc>, ClientWCF.XXX.ICalc {
        
        public CalcClient() {
        }
        
        public CalcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Soma(int x, int y) {
            return base.Channel.Soma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SomaAsync(int x, int y) {
            return base.Channel.SomaAsync(x, y);
        }
        
        public ClientWCF.XXX.Pessoa GetPessoa(string nome, int idade) {
            return base.Channel.GetPessoa(nome, idade);
        }
        
        public System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa> GetPessoaAsync(string nome, int idade) {
            return base.Channel.GetPessoaAsync(nome, idade);
        }
        
        public ClientWCF.XXX.Pessoa[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ClientWCF.XXX.Pessoa[] GetPessoas() {
            return base.Channel.GetPessoas();
        }
        
        public System.Threading.Tasks.Task<ClientWCF.XXX.Pessoa[]> GetPessoasAsync() {
            return base.Channel.GetPessoasAsync();
        }
    }
}
